# Generated by Django 4.0.3 on 2022-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0002_auto_20220401_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
