# Generated by Django 4.0.3 on 2022-04-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0004_city_remove_weather_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
