# Generated by Django 4.0.3 on 2022-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0006_weather_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
        migrations.AddField(
            model_name='weather',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
