# Generated by Django 4.0.3 on 2022-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0009_alter_city_id_alter_weather_date_alter_weather_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='field_name',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
