# Generated by Django 4.0.4 on 2022-04-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0019_date_alter_weather_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city_id',
            new_name='city',
        ),
    ]
