# Generated by Django 4.0.4 on 2022-06-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0021_roles_myuser_mailing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
