# Generated by Django 4.0.4 on 2022-06-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0022_delete_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('weather_element', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
