# Generated by Django 4.0.4 on 2022-06-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0023_weatherlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherList',
            new_name='WeatherElement',
        ),
    ]
