# Generated by Django 4.0.4 on 2022-06-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0025_alter_weather_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.TextField(blank=True, null=True),
        ),
    ]
