# Generated by Django 4.0.4 on 2022-06-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0026_alter_weather_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_admin.weatherelement'),
        ),
    ]
