# Generated by Django 4.0.4 on 2022-06-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0027_alter_weather_weather'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
    ]
