# Generated by Django 4.0.4 on 2022-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0028_rename_roles_role_remove_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
