# Generated by Django 4.0.4 on 2022-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0029_weather_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
