# Generated by Django 4.0.4 on 2022-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_admin', '0031_alter_myuser_name_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
